name: Run tests on PR

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Run tests and linting
      run: |
        npm ci
        npm run lint --if-present
        npm test
      env:
        CI: true
